apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp-deploy
  labels:
    app: java-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
        - name: java-webapp-container
          image: shinojc/java-webapp-image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-webapp-service
  labels:
    app: java-webapp
spec:
  selector:
    app: java-webapp
  type: NodePort
  ports:
    - nodePort: 30080       # Choose a port in the range 30000–32767
      port: 8080
      targetPort: 8080
